# In this nodebook, we are going to cover some of the fundamental concepts of tensors using TensorFlow

More specifically are we are going to cover:

- Introduction to tensors
- Getting information from tensor
- Manipulating Tensors
- Tensors & NumPy
- Using @tf.function (a way to speed up regular Python functions)
- Using GPUs with TensorFlow (or TPUs)
- Exercises for yourself


### Introduction to Tensors


In [13]:
# Import TensorFlow
import tensorflow as tf

tf.__version__

'2.15.0'

In [15]:
# Create tensors with tf.contants()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [16]:
# check for number of dimensions of a tensors (ndim stands for number of dimensions)
scalar.ndim

0

In [17]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [18]:
# check dimension of vector
vector.ndim

1

In [19]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [20]:
matrix.ndim

2

In [21]:
# create another matrix
another_matrix = tf.constant(
    [
        [4., 2., 7.],
        [3., 8., 10.],
        [6., 5., 9.]
    ],
    dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 4.,  2.,  7.],
       [ 3.,  8., 10.],
       [ 6.,  5.,  9.]], dtype=float16)>

In [22]:
another_matrix.ndim

2

In [23]:
# let's create a tensor with 3 dimension
tensor = tf.constant(
    [
        [
            [1, 2],
            [3, 4]
        ],

        [
            [5, 6],
            [7, 8]
        ],

        [
            [9, 10],
            [11, 12]
        ]
    ])

tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [24]:
tensor.ndim

3

What we have created so far:

- Scalar: A single number
- Vector: A number with direction (e.g. wind speed and direction)
- Matrix: A 2 dimensional array of numbers
- Tensor: A n-dimensional array of numbers (where n can be any number, 0-dimensional is a scalar, 1-dimensional is a vector)


Create tensors with tf.Variable


In [25]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
# let's try to change one of the elements in changable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>

In [ ]:
# Lets try to change unchangable_tensor
unchangeable_tensor[0].assign(3)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random Tensors

Random tensors are tensors of some arbitary size filled with random numbers


In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducability
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor


In [ ]:
# Shuffle a tensor (valuable when you want to shuffle your data so that, inhirent order does not efffect learning)
not_shuffled = tf.constant(
    [
        [10, 7],
        [3, 4],
        [2, 5]
    ]
)

# shuffle our non_shuffled tensor
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
# experementing on seed
tf.random.set_seed(55)  # global level seed
tf.random.shuffle(not_shuffled, seed=55)  # Operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

### Other ways to make tensors


In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn a numpy arrays to tensors

The main difference between NumPy Array and TensorFlow is that
tensors can be run on a GPU (much faster for numerical operations).


In [6]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)  # create a numpy between 1 to 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(3, 2, 4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [ ]:
3 * 2 * 4

24

### Getting Information from Tensors

When dealing with Tensors are probably wanted to be aware of following attributes:

- Shape
- Rank
- Axis or Dimension
- Size


In [ ]:
# Create a Rank 4 Tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Get various attributes of our tensor
print(f"DataType of every element: {rank_4_tensor.dtype}")
print(f"Number of dimensions (rank): {rank_4_tensor.ndim}")
print(f"Shape of Tensor: {rank_4_tensor.shape}")
print(f"Elements along 0 axis: {rank_4_tensor.shape[0]}")
print(f"Elements along last axis: {rank_4_tensor.shape[-1]}")
print(f"Total number of Elements in Tensor: {tf.size(rank_4_tensor)}")

DataType of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along last axis: 5
Total number of Elements in Tensor: 120


### Indexing Tensors

Tensors can be indexed just like Python list


In [ ]:
some_list= [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first elemtent from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant(
    [
        [10, 7],
        [4, 5]
    ]
)
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last element of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5], dtype=int32)>

In [ ]:
# Add a new dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 5]]], dtype=int32)>

In [ ]:
# Alternative of tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 5]]], dtype=int32)>

In [ ]:
# expand 0-axis
tf.expand_dims(rank_2_tensor, axis=0)  # '0' means expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  5]]], dtype=int32)>

### Manipulating Tensors

**Basic Operations**

+, -, *, /

In [ ]:
# You can add values to a tensor using Addition operator
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# Orginal tensor is Unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [12, 16]], dtype=int32)>

In [ ]:
# Substraction
tensor - 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-6, -5],
       [-4, -3]], dtype=int32)>

In [ ]:
# Division
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.4],
       [0.6, 0.8]])>

In [ ]:
# We can use tensor built-in functions too
tf.multiply(tensor, 10) # or use tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

**Matrix Multiplication**

In machine learninig matrix multiplication is most common tensor operations.

There are TWO rules our tensors(or matrics) need to fullfill we are going to matrix multipy them:

1. The inner dimension must match
2. The resulting matix is in the shape of outer dimensions

In [ ]:
# Matrix Multiplication in tensorflow
tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [27]:
# Create tensor of 3, 2 shape
x = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)

# Create another tensor of 3, 2 shape
y = tf.constant(
    [
        [7, 8,],
        [9, 10],
        [11, 12]
    ]
)
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Lets change the shape of y
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
x.shape, tf.reshape(y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Try to matrix multiply of same shape
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(x, shape=(2, 3)).shape, y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
# Try reshape x instead of y
tf.matmul(tf.reshape(x, shape=(2, 3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can do the same with transpose
x, tf.transpose(x), tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiply with Transpose rather than Reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Dot Product**

Matrix multiplication is also referred to as Dot Product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordor()`

In [28]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [30]:
# Perform dot product on x and y (requires x or y as transpose)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [32]:
# Perform matrix multiplication between x and y (transpose)
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [33]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [34]:
# Perform matrix multiplication between x and y (reshaped)
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Generally when performing matrix multiplication on two tensors and one of the axis does not line up, you will transpose (rather than reshape) one of the tensors to satisfy matrix multplication rules 

### Changing the datatype of Tensor

In [37]:
# Create a tensor with default dataType (float32) and shape (1, 2)
b = tf.constant([1.0, 2.0], shape=[1, 2])
b.dtype

tf.float32

In [38]:
c = tf.constant([1, 2], shape=[1, 2])
c.dtype

tf.int32

In [41]:
# Change from float32 to float16 (reduced precision)
d = tf.cast(b, dtype=tf.float16)
d, d.dtype

(<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1., 2.]], dtype=float16)>,
 tf.float16)

In [42]:
# Change from int32 to float32 
e = tf.cast(c, tf.float32)
e, c.dtype

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>,
 tf.int32)

In [44]:
e_float16 = tf.cast(e, dtype=tf.float16)
e_float16, e.dtype

(<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1., 2.]], dtype=float16)>,
 tf.float32)

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to samller amount of values.

In [2]:
# Getting the absolute values
d = tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [3]:
# Get the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation:
* Get the Minimum
* Get the Maximum
* Get the mean of a Tensor
* Get the sum of a Tensor

In [15]:
# Create a random tensor btweeen 0 to 100 of size 50
e = tf.constant(np.random.randint(low=0, high=100, size=50), dtype=tf.int32)
e

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([16, 96, 77, 60, 26, 62, 38,  9, 64, 98, 16, 92,  9, 74, 43, 32, 24,
       18, 70, 25,  6, 83, 99, 67, 29, 59,  4, 14, 51, 29, 91, 65, 16, 93,
       17, 67, 98, 13, 44, 52, 96, 54, 18, 83, 84, 63,  8, 68, 79, 17],
      dtype=int32)>

In [16]:
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [17]:
# Find the minimum of a tensor
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [18]:
# Fing the Maximum of a tensor
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [19]:
# Find the mean of a tensor
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [20]:
# Find the sum of a tensor
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int32, numpy=2516>

In [21]:
# Find the variance of e
e_mean = tf.reduce_mean(e)
e_centered = tf.subtract(e, e_mean)
e_squared = tf.square(e_centered)
variance = tf.cast(tf.reduce_mean(e_squared), dtype=tf.float32)
variance


<tf.Tensor: shape=(), dtype=float32, numpy=942.0>

In [22]:
# Find the standard deviation
standard_deviation = tf.sqrt(variance)
standard_deviation

<tf.Tensor: shape=(), dtype=float32, numpy=30.692019>

In [23]:
# Alternative appraoach to use Tensorflow Probalibilty
import tensorflow_probability as tfp

In [24]:
# Find the variance
tfp.stats.variance(e), tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int32, numpy=942>,
 <tf.Tensor: shape=(), dtype=float32, numpy=941.9377>)

In [25]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.691004>

### Find the positional maximum and minimum



In [40]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [41]:
# Find the postional maximum
tf.argmax(f), f[tf.argmax(f)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [43]:
# Find the max value of 'f'
tf.math.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [44]:
# Check for equality
f[tf.argmax(f)] == tf.math.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [47]:
# Find the postional minimum
tf.argmin(f), f[tf.argmin(f)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [48]:
# Find the minimum value of 'f'
tf.math.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [50]:
# Check for equality
f[tf.argmin(f)] == tf.math.reduce_min(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a Tesnor (removing all single dimensions)

In [65]:
# Create tensor to get started
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,2,1,25))
g

<tf.Tensor: shape=(1, 2, 1, 25), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],

        [[0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [66]:
g.shape

TensorShape([1, 2, 1, 25])

In [68]:
g_squeezed = tf.squeeze(g)
g_squeezed, g_squeezed.shape

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
         0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
         0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
        [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
         0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
         0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
         0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
         0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
       dtype=float32)>,
 TensorShape([2, 25]))

### One-hot encoding tensors

In [69]:
# create a list of indices
some_list = [0,1,2,3]

# one-hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [70]:
# Use custome values in one-hot encoding
tf.one_hot(some_list, depth=4, on_value="I love ML", off_value="I like Java")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love ML', b'I like Java', b'I like Java', b'I like Java'],
       [b'I like Java', b'I love ML', b'I like Java', b'I like Java'],
       [b'I like Java', b'I like Java', b'I love ML', b'I like Java'],
       [b'I like Java', b'I like Java', b'I like Java', b'I love ML']],
      dtype=object)>

### Tensors and Numpy

TensoFlow interacts beautifully with Numpy arrays.

In [74]:
# Create a Tensor directly from numpy array.
h = tf.constant(np.array([1, 2, 3.8, 4, 5]))
h

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1. , 2. , 3.8, 4. , 5. ])>

In [79]:
# Convert our Tensor back to Numpy array
np.array(h), type(np.array(h))

(array([1. , 2. , 3.8, 4. , 5. ]), numpy.ndarray)

In [80]:
# Convert tensor 'h' to Numpy array
h.numpy(), type(h.numpy())

(array([1. , 2. , 3.8, 4. , 5. ]), numpy.ndarray)

In [91]:
# Default types of each are slightly different.
numpy_h = tf.constant(np.array([1, 2.1, 3, 4, 5]))
tensor_h = tf.constant([1, 2.1, 3, 4, 5])

# Check the dataType of each.
numpy_h.dtype, tensor_h.dtype

(tf.float64, tf.float32)